import type { Metadata } from "next";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <head>
        <title>Your Tab Name</title>
        <link rel="icon" href="divdevs.png" />
      </head>
      <body>
        <ChakraProvider>
          {children}
          </ChakraProvider>
          </body>
    </html>
  );
}
